# Generated by Django 4.1.2 on 2023-02-21 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 21, 14, 9, 49, 600759), verbose_name='发表日期'),
        ),
    ]
