# Generated by Django 4.1.2 on 2023-02-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 21, 6, 31, 13, 515240, tzinfo=datetime.timezone.utc), verbose_name='发表日期'),
        ),
    ]
