# Generated by Django 4.1.2 on 2023-02-21 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='发表日期'),
        ),
    ]
