# Generated by Django 4.1.2 on 2023-02-23 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('blog', '0018_blogpageforapi_blogpageauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageauthor',
            name='id',
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpageauthor',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.blogpageforapi', verbose_name='所属博客'),
        ),
    ]
